.gitignore, package-lock.json, package.json, src/app/controllers/ImageController.ts, src/app/controllers/NotificationController.ts, src/app/controllers/TwilioController.ts, src/app/controllers/ValidationController.ts, src/app/models/Verify.ts, src/app/observers/Observer.ts
=> Fix TS Errors

src/app/App.ts, src/app/index.d.ts, src/index.ts
Converted App.js and index.js to TS and added declaration file
=> Convert App.js, index.js to TS

package.json, src/app/index.d.ts, tsconfig.json
Added "declaration":"true" to tsconfig
=> Add Index.d.ts

package.json, src/index.d.ts, tsconfig.json
Added to the build script to copy over the index.d.ts
=> Add to Build Script

package.json, src/app/App.ts, src/app/adaptors/CheaprEatsGraphQLAdaptor.ts, src/app/controllers/CartController.ts, src/app/controllers/CategoryController.ts, src/app/controllers/CouponController.ts, src/app/controllers/CustomerController.ts, src/app/controllers/CustomerTokenController.ts, src/app/controllers/EmployeeController.ts, src/app/controllers/ExplorePageController.ts, src/app/controllers/FlashSaleController.ts, src/app/controllers/GraphController.ts, src/app/controllers/HeadOfficeController.ts, src/app/controllers/LoyaltyCardController.ts, src/app/controllers/LoyaltyProgramController.ts, src/app/controllers/MenuItemController.ts, src/app/controllers/ModifierController.ts, src/app/controllers/OrderController.ts, src/app/controllers/PayoutController.ts, src/app/controllers/RedeemableItemController.ts, src/app/controllers/SurveyController.ts, src/app/controllers/TipController.ts, src/app/controllers/VendorController.ts, src/app/links/synchronouslinks/GraphQLLink.ts
Updated TS-SDK based on issues found in the Customer App
=> CEENG-327 Update TS-SDK

package.json, src/app/controllers/CategoryController.ts, src/app/controllers/CouponController.ts, src/app/controllers/CustomerController.ts, src/app/controllers/LoyaltyCardController.ts, src/app/links/synchronouslinks/GraphQLLink.ts
Fixed ts issues. For some reason, they weren't being flagged as errors, and when I ran tsc they didn't show up.
=> CEENG-379 Fix ts issues

README.md, package-lock.json, package.json, src/app/App.ts, src/app/controllers/CartController.ts, src/app/links/synchronouslinks/GraphQLLink.ts
=> Added shared tokens to cart, mutation for sharing cart

src/app/App.ts, src/app/controllers/ShiftController.ts, src/app/links/synchronouslinks/GraphQLLink.ts
Added three mutations for usage via the SDK:
- startShift
- endShift
- updateShiftTimePeriod
SDK builds successfully.
=> Update TS-SDK for clock-in mutation functions

package-lock.json, package.json
Increased TS-SDK version: 1.12.0
=> Increase SDK version number

package.json, src/app/controllers/VendorController.ts
=> Add interfaces for hourly sales to vendor analytics

package.json, src/app/controllers/CartController.ts
=> hotfix: Fix sharedToken param in removeItem

package.json, src/app/controllers/EmployeeController.ts, src/app/controllers/GraphController.ts
=> Add shifts interface for dynamic resolvers

package-lock.json, src/app/controllers/OrderController.ts, src/enums.ts
=> CEM-891 Ensured usage of OrderStatusEnum

src/app/controllers/PayoutController.ts, src/enums.ts
=> CEM-893 ensured usage of PayoutStatusEnum

src/app/controllers/SurveyController.ts, src/enums.ts
=> CEM-895 ensured usage of SurveyQuestionTypeEnum

src/app/controllers/CouponController.ts, src/enums.ts
=> CEM-886 Ensured usage of CouponTypeEnum

src/app/controllers/CouponController.ts, src/app/controllers/CustomerController.ts, src/enums.ts
=> CEM-884 Ensured usage of CouponTransactionTypeEnum

src/app/controllers/MenuItemController.ts, src/enums.ts
=> CEM-890 Ensured usage of MenuItemStatusEnum

src/app/controllers/MenuItemController.ts, src/enums.ts
=> CEM-888 ensured usage of FeeTypeEnum

src/app/controllers/SurveyController.ts
=> CEM-894 transpiled enums and removed duplication

package.json
=> Bumped version for auto publish

package-lock.json, package.json, src/app/controllers/CustomerController.ts, src/enums.ts
=> CEM-1017 reload customer wallet payment method enum migration

package-lock.json, package.json, src/enums.ts
=> Fixed duplicate error

package.json, src/app/controllers/PayoutController.ts
=> Fix percentage typo

package-lock.json, package.json, src/app/App.ts, src/app/controllers/OrderController.ts, src/app/links/synchronouslinks/GraphQLLink.ts
Tested working
The GraphQL mutation https://github.com/cheapreats/CheaprEats-GraphQL-API/pull/436
**Checklist:**
=> CartOrder and ReOrder mutations

package.json, src/app/controllers/MenuItemController.ts
=> Added chef_recommendation to menu item

package.json, src/app/controllers/LoyaltyProgramController.ts
=> Fix program type for loyalty program

src/app/controllers/VendorController.ts
=> CEM-1455 website_link added to Vendor

package.json, src/app/App.ts, src/app/controllers/CartController.ts, src/app/links/synchronouslinks/GraphQLLink.ts, src/enums.ts
=> SDK update for shared_token redesign

src/app/controllers/PayoutController.ts
Update Payout extends Payout using Partial and Omit
Changes made at Line 14.
=> UpdatePayoutInput interface EXTENDS PayOut

package.json, src/app/App.ts, src/app/controllers/VendorController.ts, src/app/links/synchronouslinks/GraphQLLink.ts
=> store-hours-presets-sdk-update

src/app/controllers/CouponController.ts
Re-writen 2 interfaces named:
- CreateCouponInput
- UpdateCouponInput
=> Interface CreateCoupon and UpdateCoupon extends.

src/app/controllers/LoyaltyProgramController.ts
Please, review because there are some keys inside the Update and Create LoyaltyInput interface they have Required and Partial.
=> CEM-2014 create and update Loyalty

src/app/controllers/LoyaltyCardController.ts, src/app/controllers/ModifierController.ts
=> CEM-2013 imported enums

src/app/controllers/RemoteConfigurationController.ts
=> CEM-2018 - extends one interface

src/app/controllers/VendorController.ts
I extends some interface. 
But this controller contains Vendor interface contains duplicate interface and missing keys.
=> CEM-2020 need to review Interfaces, keys.

src/app/controllers/ExplorePageController.ts
=> CEM-2012 rewritten 3 interfaces

package.json, src/app/controllers/CartController.ts, src/app/controllers/OrderController.ts
=> CEM-1229 added participating_customers to cart and order objects

package.json, src/app/controllers/CartController.ts
=> Removed shared_token from cart mutations

package.json, src/app/App.ts, src/app/controllers/CartController.ts, src/app/links/synchronouslinks/GraphQLLink.ts
=> ts-sdk update for group order mutations

src/app/controllers/VendorController.ts
=> CEM-2334 added max_in_person_subtotal_limit

src/app/App.ts, src/app/controllers/CartController.ts, src/app/controllers/OrderController.ts, src/app/links/synchronouslinks/GraphQLLink.ts
=> setTipAmount and getOrderDetails update

package.json
=> bump package

src/app/controllers/CouponController.ts
added is_storefront_visible to create and update input for Coupon
=> CEM-2216 update for is_storefront_visible

package.json
=> bump package number

package.json, src/app/controllers/CartController.ts
=> isSplitPaying update
